### ISSUE TITLE
Adopt "Validators/Eth2 Deposits" page

### ISSUE THREAD

**Issue by akolotov** [openethereum/sbc-explorer#12]
Make the following customization on the page "Validators/Eth2 Deposits":
- Rename the menu item to "Validators/<Chain name> Deposits", where`Chain name` can be configured
- Replace "Eth2 Beacon Chain" by the chain name (the same as in the previous item)
- Make the staking token symbol configurable

![image](https://user-images.githubusercontent.com/20793260/128565711-de20945b-f6bf-4d76-8b1c-ec8eee253fd6.png)

**Comment by rimrakhimov** [comment]
I've noticed that here we would like to get something like "Label Deposits" as the menu item, while in issue #10, the description says to replace "Eth1 Deposits" with "Deposits on xDai" instead of "xDai Deposits". It seems a little bit inconsistent.
